version: '3.8'

services:
  legal-search-api:
    build: . 
    container_name: legal-search-api-dummy
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./index:/app/index:ro 
      - ./metadata:/app/metadata:ro
      - ./real_pdfs:/app/pdf_data:ro
      - ./hf_cache:/root/.cache/huggingface
      - ./feedback_data:/app/feedback_data
      - /mnt/object-store-persist-group36:/app/mounted_bucket_storage:ro
      - /tmp/optimized_models:/app/optimized_models_local:ro 

    environment:
      MODEL_DEVICE_PREFERENCE: "auto" 
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1 
              capabilities: [gpu]
    networks:
      - monitoring_net

  prometheus:
    image: prom/prometheus:v2.45.0
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yaml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
    networks:
      - monitoring_net

  grafana:
    image: grafana/grafana-oss:10.2.2
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_ALLOW_SIGN_UP: 'false'
    networks:
      - monitoring_net
    depends_on:
      - prometheus

networks:
  monitoring_net:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data:
  hf_cache: