FROM nvidia/cuda:12.1.0-cudnn8-runtime-ubuntu22.04

# Set environment variables
ENV PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=off \
    PIP_DISABLE_PIP_VERSION_CHECK=on \
    # MODEL_DEVICE_PREFERENCE="gpu" \
    MODEL_DEVICE_PREFERENCE="cpu" \
    EMBEDDING_MODEL="/app/mounted_bucket_storage/model/Legal-BERT-finetuned" \
    ONNX_MODEL_PATH="/app/optimized_models_local/legal_bert_finetuned_onnx_int8_quantized" \
    FAISS_INDEX_PATH="/app/mounted_bucket_storage/faissIndex/v1/real_index.faiss" \
    FAISS_MAP_PATH="/app/mounted_bucket_storage/faissIndex/v1/real_map.pkl" \
    METADATA_PATH="/app/mounted_bucket_storage/faissIndex/v1/real_metadata.pkl" \
    PDF_DATA_DIR="/app/mounted_bucket_storage/LexisRaw" \
    MODEL_TYPE_TO_LOAD="ONNX"

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    python3-pip \
    python3-dev \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Set up a working directory
WORKDIR /app

# Copy requirements  
COPY ./requirements.txt /app/requirements.txt

# Install Python dependencies
RUN pip3 install --no-cache-dir --upgrade pip
RUN pip3 install --no-cache-dir -r requirements.txt

# Copy the rest of the application code
COPY ./src /app/src

# Expose the port the app runs on
EXPOSE 8000

# Command to run the application
CMD ["uvicorn", "src.api.main:app", "--host", "0.0.0.0", "--port", "8000"]