name: Terraform CI/CD

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Action to perform"
        required: true
        default: "apply"
        type: choice
        options:
          - apply
          - destroy

env:
  TF_VERSION: 1.6.0

jobs:
  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    environment: DEVELOPMENT
    env:
      TF_VAR_APPLICATION_CREDENTIAL_ID: ${{ secrets.APPLICATION_CREDENTIAL_ID }}
      TF_VAR_APPLICATION_CREDENTIAL_SECRET: ${{ secrets.APPLICATION_CREDENTIAL_SECRET }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Download previous terraform.tfstate if exists
        uses: actions/download-artifact@v4
        with:
          name: terraform-state
          path: terraform/
        continue-on-error: true

      - name: Terraform Init
        run: |
          terraform init \
          -backend-config="auth_url=https://chi.tacc.chameleoncloud.org:5000/v3" \
          -backend-config="user_name=${{ secrets.CHITACC_APPLICATION_CREDENTIAL_ID }}" \
          -backend-config="password=${{ secrets.CHITACC_APPLICATION_CREDENTIAL_SECRET }}" \
          -backend-config="tenant_name=89f528973fea4b3a981f9b2344e522de" \
          -backend-config="region_name=CHI@TACC"
        working-directory: terraform

      - name: Terraform Validate
        run: terraform validate
        working-directory: terraform

      - name: Terraform Plan
        run: terraform plan -out=tfplan -var-file=env/development.tfvars
        working-directory: terraform

      - name: Upload tfplan artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: terraform/tfplan

      - name: Upload updated Terraform State
        uses: actions/upload-artifact@v4
        with:
          name: terraform-state
          path: terraform/terraform.tfstate

  approval:
    name: Manual Approval
    runs-on: ubuntu-latest
    needs: plan
    environment:
      name: APPROVAL
      url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
    steps:
      - name: Wait for manual approval
        run: echo "Waiting for manual approval..."

  apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    needs: approval
    if: ${{ github.event.inputs.action == 'apply' }}
    environment: DEVELOPMENT
    env:
      TF_VAR_APPLICATION_CREDENTIAL_ID: ${{ secrets.APPLICATION_CREDENTIAL_ID }}
      TF_VAR_APPLICATION_CREDENTIAL_SECRET: ${{ secrets.APPLICATION_CREDENTIAL_SECRET }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Download tfplan artifact
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: terraform/

      - name: Download Terraform State
        uses: actions/download-artifact@v4
        with:
          name: terraform-state
          path: terraform/
        continue-on-error: true

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform Apply
        run: terraform apply tfplan
        working-directory: terraform

      - name: Upload updated Terraform State
        uses: actions/upload-artifact@v4
        with:
          name: terraform-state
          path: terraform/terraform.tfstate

  destroy:
    name: Terraform Destroy
    runs-on: ubuntu-latest
    needs: approval
    if: ${{ github.event.inputs.action == 'destroy' }}
    environment: DEVELOPMENT
    env:
      TF_VAR_APPLICATION_CREDENTIAL_ID: ${{ secrets.APPLICATION_CREDENTIAL_ID }}
      TF_VAR_APPLICATION_CREDENTIAL_SECRET: ${{ secrets.APPLICATION_CREDENTIAL_SECRET }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Download Terraform State
        uses: actions/download-artifact@v4
        with:
          name: terraform-state
          path: terraform/
        continue-on-error: true

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform Destroy
        run: terraform destroy -auto-approve -var-file=env/development.tfvars
        working-directory: terraform

      - name: Upload updated Terraform State
        uses: actions/upload-artifact@v4
        with:
          name: terraform-state
          path: terraform/terraform.tfstate
